apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      runtimeClassName: wasmedge
      nodeSelector:
        kwasm.sh/kwasm-provisioned: k3d-wasm-test-agent-0
      containers:
      - name: server
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        lifecycle:
          preStop:
            httpGet:
              path: /shutdown
              port: 8081