apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- end }}
      containers:
      - name: server
        image: {{ .Values.image }}
        env:
        - name: RUST_LOG
          value: wasi::api
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 128Mi
        lifecycle:
          preStop:
            httpGet:
              path: /shutdown
              port: 8081